### ISSUE TITLE
local_intellidata\record_deleted_observer_test::test_execute_success is failing

### ISSUE THREAD

**Issue by aneno-m-e** [intelliboard/intellidata#103]
When running the full testsuite, we ran into the following issue:

> There was 1 failure:
1) local_intellidata\record_deleted_observer_test::test_execute_success
Failed asserting that file "/home/iamtestie/sitedata/local_intellidata_testsuite177d8b/temp/ibdata/db_enrol.csv" exists.
/var/www/html/local/intellidata/tests/record_deleted_observer_test.php:101
/var/www/html/lib/phpunit/classes/advanced_testcase.php:80

Looking [at the test](https://github.com/intelliboard/intellidata/blob/main/tests/record_deleted_observer_test.php#L100, we noticed:

1) The test is checking `assertFileExists` when the comment says ` // Validate temp file not exists.`.

2) It doesn't look like data is being generated and saved so the call to StorageHelper on L103 results in `moodle_exception: File not exists`.

**Comment by vitaliikovali** [comment]
Please describe your environment where is the error.

What Moodle version?
What PHP version?
Where is moodledata (ssd, efs, s3)?
What database is used (Mysql, Mariadb, Postgre)?

**Comment by aneno-m-e** [comment]
Moodle version: 4.1
PHP version: 7.4
Moodledata: it fails regardless of storage type, but it was SSD (NVMe) for our testing pipeline
Database: PostgreSQL 12

**Comment by vitaliikovali** [comment]
Do you have any modification moodle core related to enrol or custom enrol plugin?
Because on standard moodle with this environment tests works correct.

**Comment by aneno-m-e** [comment]
Thank you for this additional information, because of it we have been able to identify that one of the custom enrol plugins was interfering with this test.

I'll close this issue as the source of it lies with us.
