### ISSUE TITLE
Problems with unit tests caused by local_intellidata

### ISSUE THREAD

**Issue by fabianbatioja** [intelliboard/intellidata#11]
Hi, 

I don't know if this is the right way to report this. I have run the unit tests for all moodle and found that local_intellidata causes about 20 tests to fail due to 2 things.

1. Most of the tests that are failing are from the mod_customcert plugin, this failure is because in `local/intellidata/classes/entities/activities/observer.php` the event of the creation of activity is handled. In line 132, it is specified what to do when the creation is of a resource of type mod_customcert. In this piece of code, we try to access the `cmid` from the instance object, but the instance is the record of the `customcert` table that does not have this attribute so it generates a debugging message and causes the unit tests to fail. This error should also be shown to the user when creating a `customcert` activity.

```
            case 'customcert':
                $params = [
                    'cmid' => $instance->cmid,
                ];
                break;
```

2. This error occurs in a non-core plugin called `block_completion_progress`. The problem is because `local/intellidata/classes/entities/assignments/observer.php` manages the events when submitting a grading, in this observer in line 121 a query is made to the `assign_submission` table, when running tests the event triggering can be simulated and this record may not be created in the table, however, the code in the observer assumes that it will always return a result and generates a debug message that causes the test to fail.
For this problem the simplest solution is to check that submission is not empty during the unit tests and if it is found to be empty terminate the execution of the method.
```
            $submission = $DB->get_record('assign_submission', [
                'assignment' => $gradedata->assignment,
                'userid' => $gradedata->userid,
                'attemptnumber' => $gradedata->attemptnumber
            ]);

            if (empty($submission) && defined('PHPUNIT_TEST') && PHPUNIT_TEST) {
                return;
            }
            $submission->grade = ((float)$gradedata->grade > 0) ? $gradedata->grade : 0;
```

The unit test that are falling:

- core_calendar_container_testcase test_delete_module_delete_events	
- mod_customcert_element_helper_testcase test_get_context_element_in_course_certificate
- mod_customcert_element_helper_testcase test_get_courseid_element_in_course_certificate
- mod_customcert_external_test_testcase test_delete_issue
- mod_customcert_external_test_testcase test_delete_issue_no_capability
- mod_customcert_external_test_testcase test_delete_issue_no_login
- mod_customcert_privacy_provider_testcase test_delete_data_for_all_users_in_context
- mod_customcert_privacy_provider_testcase test_delete_data_for_user
- mod_customcert_privacy_provider_testcase test_delete_data_for_users
- mod_customcert_privacy_provider_testcase test_export_for_context
- mod_customcert_privacy_provider_testcase test_get_contexts_for_userid
- mod_customcert_privacy_provider_testcase test_get_users_in_context
- mod_customcert_task_email_certificate_task_testcase test_email_certificates_no_cap
- mod_customcert_task_email_certificate_task_testcase test_email_certificates_no_elements
- mod_customcert_task_email_certificate_task_testcase test_email_certificates_others
- mod_customcert_task_email_certificate_task_testcase test_email_certificates_students
- mod_customcert_task_email_certificate_task_testcase test_email_certificates_students_havent_met_required_time
- mod_customcert_task_email_certificate_task_testcase test_email_certificates_students_not_visible
- mod_customcert_task_email_certificate_task_testcase test_email_certificates_t

**Comment by vlad-intelliboard** [comment]
> Hi,
> 
> I don't know if this is the right way to report this. I have run the unit tests for all moodle and found that local_intellidata causes about 20 tests to fail due to 2 things.
> 
>     1. Most of the tests that are failing are from the mod_customcert plugin, this failure is because in `local/intellidata/classes/entities/activities/observer.php` the event of the creation of activity is handled. In line 132, it is specified what to do when the creation is of a resource of type mod_customcert. In this piece of code, we try to access the `cmid` from the instance object, but the instance is the record of the `customcert` table that does not have this attribute so it generates a debugging message and causes the unit tests to fail. This error should also be shown to the user when creating a `customcert` activity.
> 
> 
> ```
>             case 'customcert':
>                 $params = [
>                     'cmid' => $instance->cmid,
>                 ];
>                 break;
> ```
> 
>     2. This error occurs in a non-core plugin called `block_completion_progress`. The problem is because `local/intellidata/classes/entities/assignments/observer.php` manages the events when submitting a grading, in this observer in line 121 a query is made to the `assign_submission` table, when running tests the event triggering can be simulated and this record may not be created in the table, however, the code in the observer assumes that it will always return a result and generates a debug message that causes the test to fail.
>        For this problem the simplest solution is to check that submission is not empty during the unit tests and if it is found to be empty terminate the execution of the method.
> 
> 
> ```
>             $submission = $DB->get_record('assign_submission', [
>                 'assignment' => $gradedata->assignment,
>                 'userid' => $gradedata->userid,
>                 'attemptnumber' => $gradedata->attemptnumber
>             ]);
> 
>             if (empty($submission) && defined('PHPUNIT_TEST') && PHPUNIT_TEST) {
>                 return;
>             }
>             $submission->grade = ((float)$gradedata->grade > 0) ? $gradedata->grade : 0;
> ```
> 
> The unit test that are falling:
> 
>     * core_calendar_container_testcase test_delete_module_delete_events
> 
>     * mod_customcert_element_helper_testcase test_get_context_element_in_course_certificate
> 
>     * mod_customcert_element_helper_testcase test_get_courseid_element_in_course_certificate
> 
>     * mod_customcert_external_test_testcase test_delete_issue
> 
>     * mod_customcert_external_test_testcase test_delete_issue_no_capability
> 
>     * mod_customcert_external_test_testcase test_delete_issue_no_login
> 
>     * mod_customcert_privacy_provider_testcase test_delete_data_for_all_users_in_context
> 
>     * mod_customcert_privacy_provider_testcase test_delete_data_for_user
> 
>     * mod_customcert_privacy_provider_testcase test_delete_data_for_users
> 
>     * mod_customcert_privacy_provider_testcase test_export_for_context
> 
>     * mod_customcert_privacy_provider_testcase test_get_contexts_for_userid
> 
>     * mod_customcert_privacy_provider_testcase test_get_users_in_context
> 
>     * mod_customcert_task_email_certificate_task_testcase test_email_certificates_no_cap
> 
>     * mod_customcert_task_email_certificate_task_testcase test_email_certificates_no_elements
> 
>     * mod_customcert_task_email_certificate_task_testcase test_email_certificates_others
> 
>     * mod_customcert_task_email_certificate_task_testcase test_email_certificates_students
> 
>     * mod_customcert_task_email_certificate_task_testcase test_email_certificates_students_havent_met_required_time
> 
>     * mod_customcert_task_email_certificate_task_testcase test_email_certificates_students_not_visible
> 
>     * mod_customcert_task_email_certificate_task_testcase test_email_certificates_t

Hello Fabian.
Thank you for your attention and request.

Team already fixed this issue and changes wll be availeble with new plugin release next week.

Thanks
Vlad Dovhan
