### ISSUE TITLE
The test `\local_intellidata\tests\local_intellidata_course_tracking_testcase::test_delete` is a Risky test

### ISSUE THREAD

**Issue by Julian-Tovar** [intelliboard/intellidata#16]
PHPUnit classifies the test `\local_intellidata\tests\local_intellidata_course_tracking_testcase::test_delete` with an R, which stands for Risky. The reason it's being considered a risky test is because the test prints output.

This test is printing output due to the call to `delete_course($course);`. This function's signature has a second argument that sets whether or not to print feedback, and this argument defaults to true. So a solution would be as simple as to set this argument to false, like this:

```delete_course($course, false);```

### Replication steps

1. Set up the PHPUnit environment.
2. Run the testcase: `\local_intellidata\tests\local_intellidata_course_tracking_testcase`

The whole testcase must be run, because the course is created on the first test, and deleted on the last one.

### Proof

This screenshot shows the result of running the whole testcase:

![image](https://user-images.githubusercontent.com/89230550/182741902-f3d9f0ff-224d-4965-81f7-7862ac52e4ce.png)

And this is the screenshot after applying the patch `delete_course($course, false);`:

![image](https://user-images.githubusercontent.com/89230550/182742086-fb0e79c6-7362-420e-b01a-3cd6dd5580f0.png)

**Comment by vlad-intelliboard** [comment]
Hello Julian,

Thank you for your request.
This will be updated in next release.

Thanks
Vlad

**Comment by vlad-intelliboard** [comment]
Hello Julian,
new plugin version released with fixed tests.

Thanks
Vlad
