### ISSUE TITLE
The files in 'amd/build' are not correctly compiled 

### ISSUE THREAD

**Issue by Julian-Tovar** [intelliboard/intellidata#17]
The files in 'amd/build', which you can see here: https://github.com/intelliboard/intellidata/tree/main/amd/build are not being correctly compiled.

First of all, minified files are commonly accompanied by a source map file, i.e. inside that directory, each file with extension 'min.js' should have an accompanying 'min.js.map' file. But not only that, because second of all, the specific file 'amd/build/lti.min.js' is not minified at all.

Please recompile the AMD files, and if possible provide them along with source maps (if not then at least minify 'amd/build/lti.min.js'). Thank you very much in advance.

**Comment by vlad-intelliboard** [comment]
Hello Julian,

we release 2 plugin version. 

[Release 1.66.0](https://github.com/intelliboard/intellidata/releases/tag/v1.66.0) - is version for Moodle 3.8 +
[Release 1.66.0 for Moodle 3.7 and older](https://github.com/intelliboard/intellidata/releases/tag/v1.66.0-Moodle37) - is version for Moodle 3.7 and older.

Thanks
Vlad
