### ISSUE TITLE
Increase the code coverage of the 'cli' directory

### ISSUE THREAD

**Issue by Julian-Tovar** [intelliboard/intellidata#18]
Good day team, I've been creating coverage reports for local_intellidata, to have an idea of how much is the code being covered:

![image](https://user-images.githubusercontent.com/89230550/183461015-fbb87960-4c57-4b0d-b368-6ce098358b43.png)

According to this report, the general coverage of local_intellidata is mid-to-low. Now, it would be unfair to create a one single issue to reach full coverage (unless said issue was an epic, or some form of meta-issue). So in this issue I wanted to talk about the 'cli' directory in particular. It seems to have 0% coverage (maybe my coverage engine is wrong?). I consider the scripts inside that directory to be very useful, and therefore deserving of proper code coverage. Thank you.

**Comment by vlad-intelliboard** [comment]
Hello Julian,

we are increaing code coverage from release to release.
As this is ongoing process we will close this issue.

Thank you for your advice.
