### ISSUE TITLE
Where do you install 'local_intelliboard_tracking' table? 

### ISSUE THREAD

**Issue by Sundayfree** [intelliboard/intellidata#42]
i do not see anywhere you install this local_intelliboard_tracking table in the plugin and this table it's used in copy_intelliboard_task. Could you tell me where do you install this table? thx in advance.

**Comment by vlad-intelliboard** [comment]
Hello.
IntelliBoard is supporting 2 versions of service.
Current plugin is IntelliBoard Next.

And also we support IntelliBoard Legacy plugin: https://github.com/intelliboard

After intellidata plugin installation - system need to copy data from legacy plugin tables, like 'local_intelliboard_tracking' to the intellidata plugin. That is why it is using cron task to migrate data between two plugins.

**Comment by Sundayfree** [comment]
Thx for ur reply that is very useful.
