### ISSUE TITLE
Every time you save on the page with custommenuitems, duplicate custom menu item is added

### ISSUE THREAD

**Issue by ericmerrill** [intelliboard/intellidata#54]
If you have the custommenuitem setting enabled, and you go to the page where the core custommenuitems is located and hit save, it will add an Analytics entry every time you save.

Code should probably (efficiently) check if the link it already there, and if so, don't re-insert it. This would also mean the site admin would be able to rearrange where it is located - not just always at the end.

**Comment by vlad-intelliboard** [comment]
Hello Eric,
we changed the mechanism of displaying Analytics link in custom menu.
Please review latest plugin release.

Thank you for request!

Best regards, 
Volodymyr Dovhan
