### ISSUE TITLE
Session held for 15-30 minutes by `local_intellidata\entities\userinfodatas\observer::user_updated`

### ISSUE THREAD

**Issue by matthewhilton** [intelliboard/intellidata#68]
After updating intellidata to version [023cd956](https://github.com/intelliboard/intellidata/tree/023cd956a673e1ed971a6906da89edc8cbcd9264) on a site many users complained they were no longer able to log in.

We use the excimer plugin https://github.com/catalyst/moodle-tool_excimer which profiles any long running task in the background.

This showed the cause of users not being able to login / getting session lock timeout errors was because of `local_intellidata\entities\userinfodatas\observer::user_updated`, see the following example profile:

![image](https://github.com/intelliboard/intellidata/assets/17095477/55f02a3a-db10-43d1-9105-7fb5214eb9cd)

The `local_intellidata\entities\userinfodatas\observer::user_updated` block took 15 minutes

Each of the `cachestore_redis::acquire_lock` blocks (the topmost ones) are approximately 1 minute long.

Note before updating intellidata, the plugin was functioning normally.

Detailed view of the descendents of one of the topmost `cachestore_redis::aquire_locks` blocks:

![image](https://github.com/intelliboard/intellidata/assets/17095477/e47e0726-8719-4332-bf6d-dc98581cf9de)

**Comment by matthewhilton** [comment]
2. Correct - https://github.com/catalyst/moodle-auth_saml2 updates user profile data from the IDP on login, triggering profile updates
3. It was previously on 62e7fef9870ba43f190ceeefa70e8a94b01b6519

**Comment by vlad-intelliboard** [comment]
Hello Matthew,

Please switch "Tracking Storage" setting to the "File" if your moodledata on SSD or to "Database" in other case.
It may overload your cache storage with custom profile fields data exported after user_updated event.

Let us know, please, if you have any issues after changing "Tracking Storage".

Thanks

**Comment by matthewhilton** [comment]
Hi @vlad-intelliboard 

I am hestitant to re-enable intellidata in production again, rightfully so, to avoid any more user disruption. So I have conducted some testing which the results you might find useful.

## Testing method
I created a script that generates `user_updated` events (so that SAML is not necessary) https://gist.github.com/matthewhilton/8241c3f9a18d7ad5ce7de5e5d46c2473

I then tested this in two environments:
1. Locally using a DB restore of the production site.
2. On a staging site.

By placing the script above into `admin/cli/generateuserevent.php` I can then call it in parallel using bash to simulate lots of events happening at once.

e.g. `sh -c 'php admin/cli/generateuserevent.php --userid=50 & php admin/cli/generateuserevent.php --userid=50 & wait`

By executing the script above in parallel using the same userid, 10 times at once, I can recreate what I think is the conditions for the original issue reported:

### Cache tracking store
**Tracking storage set to `cache`, same user 10 update events in parallel - total time 6 seconds:**
![image](https://github.com/intelliboard/intellidata/assets/17095477/ecb63c68-8602-4f73-b609-a29588531b78)

Here you can see we get a large time block for `acquire_lock` (1 second, or 20% of total time)

From a brief look at the code the cache seems to lock via a user's userid, so lots of (different) users logging in at once theoretically should not affect it. 

While this kind of looks like the original issue, I couldn't imagine more than 10 user updated events being called for a single user at once. This profile with 10 events took 6 seconds, so I'm not sure it was entirely user updated events that caused the 15 minute locks as originally reported.

This makes me think another intellidata process was also running that was holding the lock and every call to try get the lock failed / timed out (as evident by them all being 1 minute long in the original report), hence 15 lock timeouts of 1 min each = 15 mins spent holding the users session.

Of course you'd probably have a better idea of the conditions where this could happen since i am of course not an expert in intellidata code.

### File tracking store
This ran for about 10-15 minutes before I cancelled it early (hence the `default_error_handler`)

**Tracking storage set to `file`, same user 10 update events in parallel - total time 10+ mins**
![image](https://github.com/intelliboard/intellidata/assets/17095477/0e7bc696-bfdb-4405-8287-3e54d704c86d)

I recall a while ago there being issues with intelliboard and [objectfs](https://github.com/catalyst/moodle-tool_objectfs) (which this site is using). I didn't look any further into this though.

### DB tracking store
This method seemed to work as expected.

**Tracking storage set to `database`, same user 10 update events in parallel - total time ~ 2 seconds**
![image](https://github.com/intelliboard/intellidata/assets/17095477/3df1a8a5-213d-4205-8493-b0fe011aa2c1)

### Side note
It seems the slowest script in all of these profiles is `config_repository::get_optional_datatypes` - this seems to just be a repeated DB query to get records from `local_intellidata_config` - could this be optimised ?

**Comment by vlad-intelliboard** [comment]
Hi @matthewhilton 
thank you for your deep research of this issue. It is very helpful and will help us to identify the main issue for cache lock.

1. File tracking storage - it will work only with temp moodledata folder on SSD.
2. Database - it should work without any issues.
3. config_repository::get_optional_datatypes optimisation - yes, we have this in our roadmap. We will prioritise this to implement in next release.
