### ISSUE TITLE
Upgrade step error with duplicated records. 

### ISSUE THREAD

**Issue by danielcifuentesopen** [intelliboard/intellidata#75]
Hi!
After upgrading to the latest 1.119.0 version from the 1.107.0 version, I found an issue during the upgrade. I got the following error:

```
++ Error: mdb->get_record() found more than one record! ++
* line 1693 of /lib/dml/moodle_database.php: call to debugging()
* line 1651 of /lib/dml/moodle_database.php: call to moodle_database->get_record_sql()
* line 1630 of /lib/dml/moodle_database.php: call to moodle_database->get_record_select()
* line 864 of /lib/classes/persistent.php: call to moodle_database->get_record()
* line 67 of /local/intellidata/classes/repositories/config_repository.php: call to core\persistent::get_record()
* line 526 of /local/intellidata/classes/services/config_service.php: call to local_intellidata\repositories\config_repository->save()
* line 91 of /local/intellidata/classes/services/config_service.php: call to local_intellidata\services\config_service->apply_optional_tables_events()
* line 1199 of /local/intellidata/db/upgrade.php: call to local_intellidata\services\config_service->setup_config()
```

The way I found to solve this is to delete the `competency` elements from the following array in the upgrade.php file:

https://github.com/intelliboard/intellidata/blob/release/1.119.0/db/upgrade.php#L1084

My question is why are those elements in that array and is there a different or better way to solve the described error?

Thank you so much for the support.

**Comment by vlad-intelliboard** [comment]
Hello Daniel,
this code is adding/enabling Moodle tables to the IntelliData export.
In next IB Pro releases we are planning to enable competencies and tenants (MWP/Totara) data exporting by default. That is why we enabled these tables during plugin upgrade.

The error should not impact on plugin work. With updating to the latest plugin version (2023060600) the config table will be completely rebuilded, as we released one more new feature which will allow to export Moodle Native tables.

Let us know if you have any questions/prolems.

Thanks

**Comment by danielcifuentesopen** [comment]
Hi! Thank you so much for the support.
 
I see that in the latest upgrade step here https://github.com/intelliboard/intellidata/blob/release/1.119.0/db/upgrade.php#L1205, the duplicated config datatypes are deleted. Is it ok If I do it in the previous upgrade step ($oldversion < 2023060500).?  The error that I have is triggered in this line https://github.com/intelliboard/intellidata/blob/release/1.119.0/db/upgrade.php#L1199, so if I delete the duplicated datatypes before that line, I would not have the error. 

With that fix, there could be any problem or impact on plugin work? 

The code will be something like this:

```
    if ($oldversion < 2023060500) {

        // Delete old export files.
        $datatypes = datatypes_service::get_optional_datatypes_for_export();
        $exportservice = new export_service();
        $exportservice->delete_files(['datatypes' => $datatypes]);

        // Delete old datatype export ids.
        $DB->execute("DELETE FROM {local_intellidata_export_ids} WHERE datatype NOT IN
        (SELECT datatype FROM {local_intellidata_config} WHERE tabletype=:tabletype OR tabletype=:tabletype2)",
            [
                'tabletype' => datatypeconfig::TABLETYPE_REQUIRED,
                'tabletype2' => datatypeconfig::TABLETYPE_LOGS,
            ]);

        // Delete old datatype storage.
        $DB->execute("DELETE FROM {local_intellidata_storage} WHERE datatype NOT IN
        (SELECT datatype FROM {local_intellidata_config} WHERE tabletype=:tabletype OR tabletype=:tabletype2)",
            [
                'tabletype' => datatypeconfig::TABLETYPE_REQUIRED,
                'tabletype2' => datatypeconfig::TABLETYPE_LOGS
            ]);

        // Delete old datatype logs.
        $DB->execute("DELETE FROM {local_intellidata_logs} WHERE datatype NOT IN
        (SELECT datatype FROM {local_intellidata_config} WHERE tabletype=:tabletype OR tabletype=:tabletype2)",
            [
                'tabletype' => datatypeconfig::TABLETYPE_REQUIRED,
                'tabletype2' => datatypeconfig::TABLETYPE_LOGS
            ]);

        $prefix = datatypeconfig::OPTIONAL_TABLE_PREFIX;
        $DB->execute(
            "UPDATE {local_intellidata_config}
            SET datatype = CONCAT('{$prefix}', datatype)
            WHERE tabletype = :tabletype AND  datatype NOT LIKE '" . $prefix . "%'",
            [
                'tabletype' => datatypeconfig::TABLETYPE_OPTIONAL
            ]
        );

        $DB->execute(
            "UPDATE {local_intellidata_export_log}
            SET datatype = CONCAT('{$prefix}', datatype),
                last_exported_time=0,
                last_exported_id=0,
                migrated=0,
                timestart=0,
                recordsmigrated=0,
                recordscount=0
            WHERE tabletype = :tabletype AND  datatype NOT LIKE '" . $prefix . "%'",
            [
                'tabletype' => datatypeconfig::TABLETYPE_OPTIONAL
            ]
        );

        // Delete duplicates config datatypes.
        $ids = $DB->get_records_sql('SELECT max(id)
                                           FROM {local_intellidata_config}
                                       GROUP BY datatype
                                         HAVING COUNT(*) > 1');
        $ids = array_keys($ids);
        if ($ids) {
            $DB->execute("DELETE FROM {local_intellidata_config}
                            WHERE id IN (" . implode(',', $ids) . ")");
        }

        $configservice = new config_service(datatypes_service::get_all_optional_datatypes());
        $configservice->setup_config();

        upgrade_plugin_savepoint(true, 2023060500, 'local', 'intellidata');
    }

    if ($oldversion < 2023060600) {
        // Delete duplicates config datatypes.
        $ids = $DB->get_records_sql('SELECT max(id)
                                           FROM {local_intellidata_config}
                                       GROUP BY datatype
                                         HAVING COUNT(*) > 1');
        $ids = array_keys($ids);
        if ($ids) {
            $DB->execute("DELETE FROM {local_intellidata_config}
                            WHERE id IN (" . implode(',', $ids) . ")");
        }

        $datatypes = datatypes_service::get_datatypes();
        try {
            foreach ($datatypes as $datatype) {
                if (isset($datatype['table'])) {
                    $datatypename = datatypes_service::get_optional_table($datatype['name']);
                    DBHelper::remove_deleted_id_triger($datatypename, $datatype['table']);
                }
            }

            DBHelper::remove_deleted_id_functions();
        } catch (moodle_exception $e) {
            DebugHelper::error_log($e->getMessage());
        }

        $configservice = new config_service(datatypes_service::get_all_optional_datatypes());
        $configservice->setup_config();

        upgrade_plugin_savepoint(true, 2023060600, 'local', 'intellidata');
    }
```

**Comment by vlad-intelliboard** [comment]
Hi Daniel,

you can process this duplication deletion 2 times, before error and after the error as it is now:

if ($oldversion < 2023060600) {
        // Delete duplicates config datatypes.
        $ids = $DB->get_records_sql('SELECT max(id)
                                           FROM {local_intellidata_config}
                                       GROUP BY datatype
                                         HAVING COUNT(*) > 1');
        $ids = array_keys($ids);
        if ($ids) {
            $DB->execute("DELETE FROM {local_intellidata_config}
                            WHERE id IN (" . implode(',', $ids) . ")");
        }

        $datatypes = datatypes_service::get_datatypes();
        try {
            foreach ($datatypes as $datatype) {
                if (isset($datatype['table'])) {
                    $datatypename = datatypes_service::get_optional_table($datatype['name']);
                    DBHelper::remove_deleted_id_triger($datatypename, $datatype['table']);
                }
            }

            DBHelper::remove_deleted_id_functions();
        } catch (moodle_exception $e) {
            DebugHelper::error_log($e->getMessage());
        }

        $configservice = new config_service(datatypes_service::get_all_optional_datatypes());
        $configservice->setup_config();

        upgrade_plugin_savepoint(true, 2023060600, 'local', 'intellidata');
    }

Thanks

**Comment by vlad-intelliboard** [comment]
Hi Daniel,
team is checking this error and hopefully today we will update the plugin.

Thanks

**Comment by vlad-intelliboard** [comment]
Hi Daniel,

we updated the plugin with changes which will fix upgrade process.
Please review: https://github.com/intelliboard/intellidata/tree/v1.123.0

Thanks
